<a href="https://colab.research.google.com/github/nirudi98/Machine-Learning-Projects--1-/blob/main/MyFirstMachineLearning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
! pip install pandas 
print('Hello World!')

Requirement already satisfied: pandas in /usr/local/lib/python3.7/dist-packages (1.1.5)
Requirement already satisfied: python-dateutil>=2.7.3 in /usr/local/lib/python3.7/dist-packages (from pandas) (2.8.1)
Requirement already satisfied: numpy>=1.15.4 in /usr/local/lib/python3.7/dist-packages (from pandas) (1.19.5)
Requirement already satisfied: pytz>=2017.2 in /usr/local/lib/python3.7/dist-packages (from pandas) (2018.9)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.7/dist-packages (from python-dateutil>=2.7.3->pandas) (1.15.0)
Hello World!

In [3]:
import pandas as pd
#reading the csv using pandas read_csv function
df = pd.read_csv("classification_5000.csv")

#display the file read
df

              DateTime  In_Flow  In_Angle  ...  Col_density  Oxygen  Quality_type
0     2021-01-01 00:00     1.41      0.40  ...        -1.40    0.42       Premium
1     2021-01-01 01:00    -1.41     -0.02  ...         0.42   -0.10       Premium
2     2021-01-01 02:00     0.29      0.67  ...         1.48    1.11      Rejected
3     2021-01-01 03:00     2.98      1.00  ...        -2.03   -1.34      Rejected
4     2021-01-01 04:00     0.27      1.92  ...        -1.05   -1.17       Premium
...                ...      ...       ...  ...          ...     ...           ...
4995  2021-07-27 03:00     0.22     -0.42  ...        -2.06   -1.37       Premium
4996  2021-07-27 04:00     0.87     -1.54  ...         1.36   -0.86       Premium
4997  2021-07-27 05:00     0.17     -0.75  ...         0.94   -0.72      Approved
4998  2021-07-27 06:00     0.73      0.40  ...         3.36    0.76      Rejected
4999  2021-07-27 07:00    -0.05     -0.73  ...         0.93    1.60      Approved

[5000 rows x 17 columns]

In [4]:
#to display basic information about the data set
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 17 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   DateTime       5000 non-null   object
 1   In_Flow        5000 non-null   float64
 2   In_Angle       5000 non-null   float64
 3   In_Temp        5000 non-null   float64
 4   Out_Temp       5000 non-null   float64
 5   In_Pressure    5000 non-null   float64
 6   Viscosity      5000 non-null   float64
 7   Humidity       5000 non-null   float64
 8   Rot_Speed      5000 non-null   float64
 9   Valve_Opening  5000 non-null   float64
 10  Tank_%         5000 non-null   float64
 11  Out_Speed      5000 non-null   float64
 12  Thickness      5000 non-null   float64
 13  Vibration      5000 non-null   float64
 14  Col_density    5000 non-null   float64
 15  Oxygen         5000 non-null   float64
 16  Quality_type   5000 non-null   object
dtypes: float64(15), object(2)
memory usage: 664.2+ KB

In [5]:
#display numerical data only (descriptive statistics)
df.describe()

           In_Flow     In_Angle  ...  Col_density       Oxygen
count  5000.000000  5000.000000  ...  5000.000000  5000.000000
mean      0.678662    -0.014500  ...     0.710344    -0.014744
std       1.399886     1.000462  ...     1.700731     0.992921
min      -6.100000    -4.260000  ...    -6.120000    -3.750000
25%      -0.060000    -0.700000  ...    -0.340000    -0.690000
50%       0.820000    -0.020000  ...     0.740000     0.010000
75%       1.580000     0.670000  ...     1.830000     0.660000
max       5.080000     3.310000  ...     6.830000     3.630000

[8 rows x 15 columns]

In [6]:
#creates correlation matrix to identify basic relationships between variables
df.corr()

                In_Flow  In_Angle   In_Temp  ...  Vibration  Col_density    Oxygen
In_Flow        1.000000 -0.003215 -0.013636  ...  -0.006062    -0.038673 -0.000930
In_Angle      -0.003215  1.000000 -0.021197  ...  -0.023547     0.021942 -0.003048
In_Temp       -0.013636 -0.021197  1.000000  ...  -0.002501     0.013037 -0.000689
Out_Temp       0.052537 -0.011058  0.017025  ...  -0.010388    -0.034745 -0.015645
In_Pressure    0.225834  0.020030 -0.005671  ...   0.014644    -0.352036  0.009033
Viscosity     -0.005518  0.011512 -0.004853  ...  -0.007153    -0.016358 -0.007108
Humidity       0.577518  0.012110 -0.018469  ...   0.005821    -0.002687  0.034456
Rot_Speed      0.563143 -0.020147  0.008818  ...  -0.015282    -0.166462 -0.034626
Valve_Opening -0.020819 -0.013598 -0.020885  ...   0.013938    -0.002074 -0.012193
Tank_%        -0.107559  0.004809 -0.012042  ...   0.006652    -0.066817  0.040016
Out_Speed      0.005053  0.004233 -0.002168  ...  -0.008690     0.005061  0.003664
Thickness     -0.022900  0.015907  0.012368  ...  -0.024009     0.006112 -0.018229
Vibration     -0.006062 -0.023547 -0.002501  ...   1.000000    -0.003732 -0.022625
Col_density   -0.038673  0.021942  0.013037  ...  -0.003732     1.000000 -0.000561
Oxygen        -0.000930 -0.003048 -0.000689  ...  -0.022625    -0.000561  1.000000

[15 rows x 15 columns]

In [7]:
df.head()

           DateTime  In_Flow  In_Angle  ...  Col_density  Oxygen  Quality_type
0  2021-01-01 00:00     1.41      0.40  ...        -1.40    0.42       Premium
1  2021-01-01 01:00    -1.41     -0.02  ...         0.42   -0.10       Premium
2  2021-01-01 02:00     0.29      0.67  ...         1.48    1.11      Rejected
3  2021-01-01 03:00     2.98      1.00  ...        -2.03   -1.34      Rejected
4  2021-01-01 04:00     0.27      1.92  ...        -1.05   -1.17       Premium

[5 rows x 17 columns]

In [8]:
df.tail()

              DateTime  In_Flow  In_Angle  ...  Col_density  Oxygen  Quality_type
4995  2021-07-27 03:00     0.22     -0.42  ...        -2.06   -1.37       Premium
4996  2021-07-27 04:00     0.87     -1.54  ...         1.36   -0.86       Premium
4997  2021-07-27 05:00     0.17     -0.75  ...         0.94   -0.72      Approved
4998  2021-07-27 06:00     0.73      0.40  ...         3.36    0.76      Rejected
4999  2021-07-27 07:00    -0.05     -0.73  ...         0.93    1.60      Approved

[5 rows x 17 columns]

In [12]:
#import the function to randomly split dataset into training and testing
from sklearn.model_selection import train_test_split

#extracts the quality type to create a y data frame
y = df["Quality_type"]

#drop the unnecessary columns and add the rest to X dataframe
X = df.drop(["DateTime","Quality_type"],axis=1)

#split X and y vectors into training (80%) and testing (20%)
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.20,random_state=22)

print("X_train =", X_train.shape)
print("X_test = ", X_test.shape)
print("y_train = ", y_train.shape)
print("y_test = ", y_test.shape)

X_train = (4000, 15)
X_test =  (1000, 15)
y_train =  (4000,)
y_test =  (1000,)

In [13]:
#importing machine learning algorithm : random forest regressor
from sklearn.ensemble import RandomForestClassifier

#declare rfr as random forest algorithm
rfr = RandomForestClassifier()

#launch random forest training
rfr.fit(X_train,y_train)

RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=None, max_features='auto',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=100,
                       n_jobs=None, oob_score=False, random_state=None,
                       verbose=0, warm_start=False)

In [14]:
#evalutes the performance of the training set
rfr.score(X_train,y_train)

1.0

In [15]:
#evalute performance of the test set 
rfr.score(X_test,y_test)

0.804

In [16]:
#comparing prediction with actual values
df["Quality_prediction"] = rfr.predict(X)
df.sample(15, random_state=22)

              DateTime  In_Flow  ...  Quality_type  Quality_prediction
1332  2021-02-25 12:00    -0.52  ...       Premium            Rejected
2844  2021-04-28 12:00     1.15  ...      Approved            Approved
4665  2021-07-13 09:00     0.92  ...       Premium            Rejected
3408  2021-05-22 00:00     3.16  ...      Rejected            Rejected
975   2021-02-10 15:00     1.55  ...      Rejected            Approved
283   2021-01-12 19:00     2.29  ...       Premium            Rejected
4982  2021-07-26 14:00     0.32  ...       Premium             Premium
4880  2021-07-22 08:00    -0.93  ...      Approved            Approved
2981  2021-05-04 05:00     1.19  ...       Premium             Premium
1830  2021-03-17 06:00    -1.51  ...      Approved             Premium
3058  2021-05-07 10:00    -0.30  ...      Rejected            Rejected
3593  2021-05-29 17:00     1.91  ...      Approved            Approved
3219  2021-05-14 03:00     2.69  ...      Rejected             Premium
1840  2021-03-17 16:00    -2.98  ...      Approved             Premium
1838  2021-03-17 14:00     1.85  ...      Approved            Approved

[15 rows x 18 columns]

In [17]:
#raw features importance display
rfr.feature_importances_

array([0.0775844 , 0.03508154, 0.03530473, 0.16054563, 0.11691644,
       0.03487014, 0.07924378, 0.08460746, 0.03478204, 0.0893325 ,
       0.03430924, 0.03446914, 0.03332111, 0.11337422, 0.03625765])

In [19]:
#creating dataframe with the features importance
rfr_imp = pd.DataFrame(rfr.feature_importances_,columns=["Importance"])

#multiplying the importance value with 100 to ease the reading
rfr_imp["Importance"] = rfr_imp["Importance"]*100

#using the features names as index
rfr_imp = rfr_imp.set_index([X.columns])

#displayingt the dataframe with desecending importance values
display(rfr_imp.sort_values(by="Importance", ascending=False))

               Importance
Out_Temp        16.054563
In_Pressure     11.691644
Col_density     11.337422
Tank_%           8.933250
Rot_Speed        8.460746
Humidity         7.924378
In_Flow          7.758440
Oxygen           3.625765
In_Temp          3.530473
In_Angle         3.508154
Viscosity        3.487014
Valve_Opening    3.478204
Thickness        3.446914
Out_Speed        3.430924
Vibration        3.332111